# Generated by Django 3.1.2 on 2025-02-20 10:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShapeCheckProcessState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_type', models.PositiveSmallIntegerField(choices=[(1, 'copia'), (2, 'calcolo'), (3, 'salvataggio'), (4, 'log')])),
                ('sheet_name', models.CharField(max_length=100)),
                ('file_name', models.CharField(default='', max_length=100)),
                ('import_start_timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('import_end_timestamp', models.DateTimeField(null=True)),
                ('status', models.CharField(default='QUEUED', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Task_CheckShape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('schema', models.CharField(max_length=250)),
                ('imported', models.BooleanField(blank=True, default=False)),
                ('exported', models.BooleanField(blank=True, default=False)),
                ('check_type', models.CharField(default='ACQ', max_length=5)),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='QUEUED', max_length=20)),
                ('logfile', models.CharField(blank=True, default=None, max_length=300)),
                ('progress', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='XlsxDbf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('analysis_year', models.CharField(default='Current', max_length=10)),
            ],
        ),
        migrations.AddConstraint(
            model_name='xlsxdbf',
            constraint=models.UniqueConstraint(fields=('name', 'analysis_year'), name='unique_xlsx_dbf_name_year'),
        ),
        migrations.AddField(
            model_name='task_checkshape',
            name='requesting_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task_checkshape',
            name='xlsx_dbf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shape_checks.xlsxdbf'),
        ),
        migrations.AddField(
            model_name='shapecheckprocessstate',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shape_checks.task_checkshape'),
        ),
    ]
