# Generated by Django 3.1.2 on 2025-07-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shape_checks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_checkshape',
            name='group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
