version: "3.8"
services:
  ldap: 
    image: dwimberger/ldap-ad-it
    ports:
      - "10389:10389"
  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
  db:
    image: kartoza/postgis
    ports:
      - "5432:5432"
    environment: 
        - POSTGRES_USER=postgres
        - POSTGRES_PASS=j05hhome
        - POSTGRES_DBNAME=dbiait
        - POSTGRES_MULTIPLE_EXTENSIONS=postgis
  web:
    image: dbiait-web
    environment: 
        - LDAP_HOST=ldap
        - DRAMATIQ_BROKER_URL=rabbitmq
        # - DATABASE_NAME=dbiait
        # - DATABASE_USER=postgres
        # - DATABASE_PASSWORD=j05hhome
        # - DATABASE_HOST=db
    depends_on: 
      - ldap
      - db
      - rabbitmq
    ports:
      - "8000:8000"
  # dramatiq:
  #   image: dramatiq
  #   environment:
  #       - DRAMATIQ_BROKER_URL=rabbitmq
  #       # - DATABASE_NAME=dbiait
  #       # - DATABASE_USER=postgres
  #       # - DATABASE_PASSWORD=j05hhome
  #       # - DATABASE_HOST=db
  #   depends_on: 
  #     - db
  #     - rabbitmq
  #   ports:
  #     - "9191:9191"
