services:
  dbiait:
    container_name: dbiait
    build:
      context: ./
      dockerfile: Dockerfile
    command: ["/bin/bash", "-c", "source /opt/conda/etc/profile.d/conda.sh && conda activate dbiait && gunicorn -c /usr/src/dbiait/deploy/gunicorn.conf.py"]
    ports:
      - "8001:8000"
    env_file:
      - .env
  #dramatiq:
  #  container_name: dramatiq
  #  build:
  #    context: ./
  #    dockerfile: Dockerfile
  #  entrypoint: sleep infinity
  #  ports:
  #    - "8000:8000"
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.13-management
    env_file:
      - .env
  db:
    container_name: postgres
    image: postgis/postgis:15-3.4-alpine
    environment:
      "POSTGRES_PASSWORD": "password"
    env_file:
      - .env
    volumes:
      - dbdata:/var/lib/postgresql/data
  
volumes:
  dbiait:
    name: dbiait-project
  dbdata:
    name: dbiait-dbdata