# Generated by Django 3.1.2 on 2020-10-23 08:01

import app.scheduler.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('schema', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='QUEUED', max_length=20)),
                ('logfile', models.CharField(blank=True, default=None, max_length=300)),
                ('params', models.JSONField(blank=True, default=app.scheduler.models.default_storage, help_text='Task arguments.')),
                ('progress', models.IntegerField(default=0)),
                ('geopackage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.geopackage')),
                ('requesting_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
