# Generated by Django 3.1.2 on 2020-11-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_auto_20201102_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllDomains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominio_gis', models.CharField(max_length=50)),
                ('valore_gis', models.CharField(max_length=100)),
                ('descrizione_gis', models.CharField(max_length=255, null=True)),
                ('dominio_netsic', models.CharField(max_length=50, null=True)),
                ('valore_netsic', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'all_domains',
                'managed': False,
            },
        ),
    ]
