# Generated by Django 3.1.2 on 2020-10-29 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_process_processhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='geopackage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.geopackage'),
        ),
    ]
