# Generated by Django 3.1.2 on 2020-11-13 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_importedlayer'),
        ('scheduler', '0003_alldomains'),
    ]

    operations = [
    ]
