# Generated by Django 3.1.2 on 2020-11-16 15:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_merge_20201116_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='importedlayer',
            old_name='import_date',
            new_name='import_end_date',
        ),
        migrations.AddField(
            model_name='importedlayer',
            name='import_start_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
