# Generated by Django 3.1.2 on 2020-12-09 12:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0013_importedlayer_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreezeLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freeze_start_timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('freeze_end_timestamp', models.DateTimeField(null=True)),
                ('layer_name', models.CharField(max_length=250)),
                ('status', models.CharField(default='QUEUED', max_length=20)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.task')),
            ],
        ),
    ]
