# Generated by Django 3.1.2 on 2023-01-24 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0015_freeze'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVFileUploaded',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('ingestion_time', models.DateTimeField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.task')),
            ],
        ),
    ]
