# Generated by Django 3.1.2 on 2020-12-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0015_freeze'),
    ]

    operations = [
        migrations.CreateModel(
            name='CondottaEdge',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('idgis', models.CharField(max_length=32)),
                ('source', models.IntegerField()),
                ('target', models.IntegerField()),
            ],
            options={
                'db_table': 'acq_condotta_edges',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CondottaNode',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'acq_condotta_nodes',
                'managed': False,
            },
        ),
    ]
