# Generated by Django 3.1.2 on 2020-12-14 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0016_condottaedge_condottanode'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='condottaedge',
            table='dbiait_analysis"."acq_condotta_edges',
        ),
        migrations.AlterModelTable(
            name='condottanode',
            table='dbiait_analysis"."acq_condotta_nodes',
        ),
    ]
