version: "3.8"
services:

  nginx:
   image: nginx
   deploy:
     replicas: 1
   restart: unless-stopped
   container_name: nginx
   depends_on:
     - webapp
   ports:
     - "8080:80"
     - "8443:443"
   volumes:
     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
     - ./nginx/dbiait.conf:/etc/nginx/sites-enabled/dbiait.conf
     - ./nginx/localhost.key:/etc/nginx/localhost.key
     - ./nginx/localhost.crt:/etc/nginx/localhost.crt

  webapp:
   image: dbiait
   deploy:
     replicas: 1
   restart: unless-stopped
   container_name: webapp
   #depends_on:
   #  - rabbitmq
   ports:
     - "8000"
   #configs:
   #  - my_config

#configs:
#  nginx_conf:
#    file: ./nginx.conf
#  dbiait_conf:
#    file: ./nginx.dbiait_nginx.conf
