# Generated by Django 3.1.2 on 2025-02-04 08:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Xlsx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
                ('file_path', models.CharField(max_length=300, null=True)),
                ('second_file_path', models.CharField(max_length=300, null=True)),
                ('analysis_year', models.CharField(default='Current', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Task_CheckDbi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('schema', models.CharField(max_length=250)),
                ('imported', models.BooleanField(blank=True, default=False)),
                ('exported', models.BooleanField(blank=True, default=False)),
                ('check_type', models.CharField(choices=[('CDO', 'Consistenza delle opere'), ('DP', 'Dati prioritati')], default='CDO', max_length=5)),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='QUEUED', max_length=20)),
                ('logfile', models.CharField(blank=True, default=None, max_length=100)),
                ('progress', models.IntegerField(default=0)),
                ('requesting_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('xlsx', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dbi_checks.xlsx')),
            ],
        ),
        migrations.CreateModel(
            name='ImportedSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(max_length=100)),
                ('file_name', models.CharField(default='file.xlsx', max_length=100)),
                ('import_start_timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('import_end_timestamp', models.DateTimeField(null=True)),
                ('status', models.CharField(default='QUEUED', max_length=20)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbi_checks.task_checkdbi')),
            ],
        ),
    ]
