# Generated by Django 3.1.2 on 2025-01-19 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Xlsx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task_CheckDbi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('schema', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=300)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='QUEUED', max_length=20)),
                ('logfile', models.CharField(blank=True, default=None, max_length=300)),
                ('progress', models.IntegerField(default=0)),
                ('requesting_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('xlsx', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dbi_checks.xlsx')),
            ],
        ),
    ]
