# Generated by Django 3.1.2 on 2025-02-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbi_checks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xlsx',
            old_name='file_path1',
            new_name='file_path',
        ),
        migrations.RenameField(
            model_name='xlsx',
            old_name='file_path2',
            new_name='second_file_path',
        ),
        migrations.RemoveField(
            model_name='task_checkdbi',
            name='params',
        ),
        migrations.AddField(
            model_name='task_checkdbi',
            name='check_type',
            field=models.CharField(default='CDO', max_length=5),
        ),
        migrations.AlterField(
            model_name='importedsheet',
            name='file_name',
            field=models.CharField(default='file.xlsx', max_length=100),
        ),
        migrations.AlterField(
            model_name='importedsheet',
            name='sheet_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='task_checkdbi',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
