# Generated by Django 3.1.2 on 2025-01-30 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbi_checks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task_checkdbi',
            name='params',
        ),
    ]
