# Generated by Django 3.1.2 on 2025-02-07 14:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbi_checks', '0002_auto_20250205_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_type', models.PositiveSmallIntegerField(choices=[(1, 'Dati copiati'), (2, 'Formule calcolate'), (3, 'File salvato'), (4, 'Log creati')])),
                ('sheet_name', models.CharField(max_length=100)),
                ('file_name', models.CharField(default='', max_length=100)),
                ('import_start_timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('import_end_timestamp', models.DateTimeField(null=True)),
                ('status', models.CharField(default='QUEUED', max_length=20)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbi_checks.task_checkdbi')),
            ],
        ),
        migrations.DeleteModel(
            name='ImportedSheet',
        ),
    ]
