# Generated by Django 3.1.2 on 2025-01-30 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbi_checks', '0002_remove_task_checkdbi_params'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xlsx',
            old_name='file_path1',
            new_name='file_path',
        ),
        migrations.RenameField(
            model_name='xlsx',
            old_name='file_path2',
            new_name='second_file_path',
        ),
    ]
