# Generated by Django 3.1.2 on 2025-01-20 13:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbi_checks', '0002_remove_task_checkdbi_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_start_timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('import_end_timestamp', models.DateTimeField(null=True)),
                ('sheet_name', models.CharField(max_length=250)),
                ('status', models.CharField(default='QUEUED', max_length=20)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbi_checks.task_checkdbi')),
            ],
        ),
    ]
