# Generated by Django 3.1.2 on 2025-02-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbi_checks', '0003_auto_20250207_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processstate',
            name='process_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'copia'), (2, 'calcolo'), (3, 'salvataggio'), (4, 'log')]),
        ),
    ]
