# Generated by Django 3.1.2 on 2025-01-21 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbi_checks', '0003_importedsheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_checkdbi',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
