# Generated by Django 3.1.2 on 2025-02-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbi_checks', '0003_auto_20250204_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_checkdbi',
            name='check_type',
            field=models.CharField(choices=[('CDO', 'Consistenza delle opere'), ('DP', 'Dati prioritati')], default='CDO', max_length=5),
        ),
    ]
