# Generated by Django 3.1.2 on 2025-02-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbi_checks', '0003_auto_20250130_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_checkdbi',
            name='check_type',
            field=models.CharField(default=False, max_length=20),
        ),
    ]
