# Generated by Django 3.1.2 on 2025-01-21 08:05

import app.scheduler.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbi_checks', '0004_task_checkdbi_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_checkdbi',
            name='params',
            field=models.JSONField(blank=True, default=app.scheduler.utils.default_storage, help_text='Task arguments.'),
        ),
    ]
