# Generated by Django 3.1.2 on 2025-02-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbi_checks', '0004_auto_20250204_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_checkdbi',
            name='check_type',
            field=models.CharField(default='CDO', max_length=5),
        ),
    ]
