# Generated by Django 3.1.2 on 2025-02-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbi_checks', '0004_auto_20250210_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xlsx',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AddConstraint(
            model_name='xlsx',
            constraint=models.UniqueConstraint(fields=('name', 'analysis_year'), name='unique_name_year'),
        ),
    ]
