# Generated by Django 3.1.2 on 2025-02-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbi_checks', '0004_auto_20250210_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xlsx',
            name='name',
            field=models.CharField(max_length=300),
        ),
    ]
