# Generated by Django 3.1.2 on 2025-02-03 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbi_checks', '0004_task_checkdbi_check_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task_checkdbi',
            name='check_type',
        ),
    ]
