# Generated by Django 3.1.2 on 2025-01-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbi_checks', '0005_task_checkdbi_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='xlsx',
            name='file_path1',
            field=models.CharField(default='/home/gpetr/geosol/projects/DBIAIT2/C179-DBIAIT/app/dbi_checks/uploaded_xlsx_files/file1', max_length=300),
        ),
        migrations.AddField(
            model_name='xlsx',
            name='file_path2',
            field=models.CharField(default='/home/gpetr/geosol/projects/DBIAIT2/C179-DBIAIT/app/dbi_checks/uploaded_xlsx_files/file2', max_length=300),
        ),
    ]
