# Generated by Django 3.1.2 on 2025-02-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbi_checks', '0005_auto_20250213_0911'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='xlsx',
            constraint=models.UniqueConstraint(fields=('name', 'analysis_year'), name='unique_name_year'),
        ),
    ]
