# Generated by Django 3.1.2 on 2025-02-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbi_checks', '0005_remove_task_checkdbi_check_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_checkdbi',
            name='check_type',
            field=models.CharField(default=False, max_length=20),
        ),
    ]
