# Generated by Django 3.1.2 on 2025-02-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbi_checks', '0005_auto_20250204_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task_checkdbi',
            name='logfile',
            field=models.CharField(blank=True, default=None, max_length=300),
        ),
    ]
