# Generated by Django 3.1.2 on 2025-07-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbi_checks', '0005_auto_20250213_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_checkdbi',
            name='group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
