# Generated by Django 3.1.2 on 2025-01-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbi_checks', '0006_auto_20250122_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xlsx',
            name='name',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
