# Generated by Django 3.1.2 on 2025-01-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbi_checks', '0007_auto_20250122_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='importedsheet',
            name='file_name',
            field=models.CharField(default='/home/gpetr/geosol/projects/DBIAIT2/C179-DBIAIT/app/dbi_checks/download/file.xlsx', max_length=250),
        ),
        migrations.AlterField(
            model_name='xlsx',
            name='file_path1',
            field=models.CharField(default='/home/gpetr/geosol/projects/DBIAIT2/C179-DBIAIT/app/dbi_checks/uploaded_xlsx_files/file1.xlsx', max_length=300),
        ),
        migrations.AlterField(
            model_name='xlsx',
            name='file_path2',
            field=models.CharField(default='/home/gpetr/geosol/projects/DBIAIT2/C179-DBIAIT/app/dbi_checks/uploaded_xlsx_files/file2.xlsx', max_length=300),
        ),
    ]
