# Generated by Django 3.1.2 on 2025-01-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbi_checks', '0008_auto_20250122_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedsheet',
            name='file_name',
            field=models.CharField(default='file.xlsx', max_length=250),
        ),
    ]
