# Generated by Django 3.1.2 on 2025-01-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbi_checks', '0009_auto_20250122_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xlsx',
            name='file_path1',
            field=models.CharField(default='/home/gpetr/geosol/projects/DBIAIT2/C179-DBIAIT/app/dbi_checks/checks_uploaded_files/file1.xlsx', max_length=300),
        ),
        migrations.AlterField(
            model_name='xlsx',
            name='file_path2',
            field=models.CharField(default='/home/gpetr/geosol/projects/DBIAIT2/C179-DBIAIT/app/dbi_checks/checks_uploaded_files/file2.xlsx', max_length=300),
        ),
    ]
