# Generated by Django 3.1.2 on 2025-01-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbi_checks', '0010_auto_20250122_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='xlsx',
            name='analysis_year',
            field=models.CharField(default='Current', max_length=10),
        ),
    ]
