# Generated by Django 3.1.2 on 2025-01-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbi_checks', '0011_xlsx_analysis_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task_checkdbi',
            name='type',
        ),
        migrations.AddField(
            model_name='task_checkdbi',
            name='exported',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='task_checkdbi',
            name='imported',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
