# Generated by Django 3.1.2 on 2025-01-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbi_checks', '0012_auto_20250126_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xlsx',
            name='file_path1',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='xlsx',
            name='file_path2',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
